spring:
  profiles:
    active: local

---
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: test
      password: test
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile:
  sql:
    init:
      platform: h2
