### shops findAll
GET http://localhost:8080/api/shops

### shops create
POST http://localhost:8080/api/shops
Content-Type: application/json

{
  "name": "shop"
}

### shops update
PUT http://localhost:8080/api/shops/1
Content-Type: application/json

{
  "name": "shop2"
}
